# Numpy

In [1]:
### pip install numpy
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

### One Dimension Array

In [3]:
np1 = np.arange(4)

In [4]:
np1

array([0, 1, 2, 3])

In [6]:
type(np1)

numpy.ndarray

In [8]:
np1.shape # Rows, Columns

(4,)

## Two Dimension Array

In [11]:
np2 = np.arange(6).reshape(3,2)
np2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
np2.shape

(3, 2)

### N Dimension Array

In [16]:
np3 = np.arange(24).reshape(3,2,4)
np3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
np3 = np.arange(12).reshape(2,2,3)
np3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
npstr = np.arange("welcome")

TypeError: ignored

In [19]:
npstr = np.array(["welcome"])

In [20]:
npstr

array(['welcome'], dtype='<U7')

### Declare with datatypes

In [23]:
npflt = np.array([1,2,3,4], dtype=float)

In [24]:
npflt

array([1., 2., 3., 4.])

In [25]:
type(npflt)

numpy.ndarray

In [26]:
npflt.dtype

dtype('float64')

In [27]:
npint = np.array([1,2,3,4])
npint.dtype

dtype('int64')

### Reshaping the array dimension

In [28]:
np4 = np.arange(32)

In [29]:
np4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [30]:
np4.shape

(32,)

In [31]:
np4x8 = np4.reshape(4,8)
np4x8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [32]:
np2x16 = np4.reshape(2,16)
np2x16

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [33]:
np16x2 = np4.reshape(16,2)
np16x2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [34]:
np16x2.T

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]])

In [36]:
np4x4x2 = np4.reshape(4,4,2) # 4 Blocks, 4 Rows and 2 Columns
np4x4x2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [37]:
np8x_ = np4.reshape(8,-1)
np8x_

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [40]:
np4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

### Auto Reshaping

In [41]:
np8x1x_ = np4.reshape(8,1,-1)
np8x1x_

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]],

       [[12, 13, 14, 15]],

       [[16, 17, 18, 19]],

       [[20, 21, 22, 23]],

       [[24, 25, 26, 27]],

       [[28, 29, 30, 31]]])

### Numpy Operations

In [42]:
np8x_

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
np8x_.shape

(8, 4)

### Elementwise addition

In [49]:
np8x4_1 = np.add(np8x_, np8x_)
np8x4_1

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46],
       [48, 50, 52, 54],
       [56, 58, 60, 62]])

In [51]:
np8x4_2 = np8x4_1 + np8x_
np8x4_2

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69],
       [72, 75, 78, 81],
       [84, 87, 90, 93]])

### Elementwise Multiply

In [57]:
np8x_ = np.arange(6).reshape(3,-1)
np8x_

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
np8x_mul = np8x_ * np8x_
np8x_mul

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

### Matrix Multiply

In [61]:
np2x3 = np8x_mul.reshape(2,3)
np2x3

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [62]:
np8x_mul

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [67]:
np8x_matmul = np8x_mul @ np2x3
np8x_matmul

array([[  9,  16,  25],
       [ 81, 148, 241],
       [225, 416, 689]])

In [64]:
np8x_matmul =  np2x3 @ np8x_mul
np8x_matmul

array([[ 68, 109],
       [464, 778]])

### ArgMax

In [76]:
np3x2 = np.array([[1,3,2],[5,4,7]])
np3x2

array([[1, 3, 2],
       [5, 4, 7]])

In [77]:
np.argmax(np3x2)

5

In [78]:
np.argmax(np3x2, axis=0) # columns

array([1, 1, 1])

In [79]:
np.argmax(np3x2, axis=1) # row

array([1, 2])

### ArgMin

In [80]:
np.argmin(np3x2)

0

In [81]:
np.argmin(np3x2, axis=0) # columns

array([0, 0, 0])

In [82]:
np.argmin(np3x2, axis=1) # row

array([0, 1])

### Mean

In [84]:
np3x2

array([[1, 3, 2],
       [5, 4, 7]])

In [85]:
np.mean(np3x2)

3.6666666666666665

In [86]:
np.sqrt(np3x2)

array([[1.        , 1.73205081, 1.41421356],
       [2.23606798, 2.        , 2.64575131]])

In [88]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Slicing

In [101]:
np2x4x_ = np4.reshape(2,4,-1)
np2x4x_

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [103]:
np2x4x_[0,1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [105]:
np2x4x_[0,2:4,0:2]

array([[ 8,  9],
       [12, 13]])

In [93]:
|np3x2[0]

array([1, 3, 2])

In [96]:
np3x2[:,1]

array([3, 4])